### ISSUE TITLE
Threshold size method?

### ISSUE THREAD

**Issue by zvezdochiot** [hsnr-gamera/gamera#27]
:question: Maybe add size method?

```
Is <- thumbnail(I, WxH -> RxR) //small image
Ib <- bicubic(Is, RxR -> WxH) //upscale small image
Ith <- (sign(I - Ib + delta) < 0) ? 0 : 255 //threshold
```

:link: See also https://github.com/jwilk/didjvu/issues/15

**Comment by cdalitz** [comment]
This is already implemented. It is not listed among the properties of the *Image* class because this property is inherited from the *Rect* class. Nevertheless, you can just call

    # obtain a Size object
    s = image.size
    # extract width and height
    h = s.height
    w = s.width

**Comment by zvezdochiot** [comment]
Hi, @cdalitz .

:warning: Misunderstanding came out. The question was about the threshold method using scaling.

**Comment by cdalitz** [comment]
Can you please give a reference to an article describing this thresholding method? It seems to be directly applicable to color images, and thus it might be  valuable addition.

**Comment by zvezdochiot** [comment]
Hi @cdalitz .

:information_source: This method is not described anywhere. It is based on the general theory of the “threshold surface” of local threshold methods. The only innovation is the use of scaling algorithms to obtain a “threshold surface”.

This method was experimentally tested using scaling algorithms "gample" and "bicubic" in the project https://github.com/ImageProcessing-ElectronicPublications/imthreshold . The framework of the method was the algorithm "sauvola".

Also, when developing the method, the experience of using integrated images was considered (this method is largely similar to them):
* https://github.com/ImageProcessing-ElectronicPublications/aithreshold
* https://github.com/ImageProcessing-ElectronicPublications/imgtxtenh

**Comment by cdalitz** [comment]
Understanding the algorithm from the code of an implementation alone is too cumbersome. Can you please provide a publication that describes the algorithm in sufficient detail to implment it thereafter? Thanks.

**Comment by zvezdochiot** [comment]
@cdalitz say:
>Can you please provide a publication that describes the algorithm in sufficient detail to implment it thereafter?

There is no such publication (I don’t know such), only an experimental scheme. I'm sorry.

**Comment by zvezdochiot** [comment]
no actual.
