### ISSUE TITLE
Grouped glyphs getting created every time Group and Guess All

### ISSUE THREAD

**Issue by pf-physics** [hsnr-gamera/gamera#8]
(Using Gamera version 3.4.3)
If you use "group and guess all" more than once, duplicates of glyphs will get created. (Gamera keeps looking at the _group._part glyphs and groups them every time the function is called.)

I used this image. I grouped one of the 'i's as _group.i
![test_image](https://user-images.githubusercontent.com/11495571/28481319-78aed2cc-6e32-11e7-8f3a-af50d0aa86ad.png)

The first time I grouped them, these are the glyphs I got. There is already an extra i.
![first_group](https://user-images.githubusercontent.com/11495571/28482224-7820dd02-6e35-11e7-891c-9092c6fb2919.png)

The second time I grouped them, there were double the number of 'i's.
![second_group](https://user-images.githubusercontent.com/11495571/28482255-92875f18-6e35-11e7-99da-e6c3302fdc11.png)

Further grouping caused some of the 'i's to be placed into the _group._part.i

**Comment by cdalitz** [comment]
Thanks for the detailed bug report. It may take some time before I can have a look into this, though.

**Comment by cdalitz** [comment]
This is now fixed in the git repository. Please checkout the Gamera sources again.
